# Generated by Django 5.0.1 on 2024-01-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bear', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='images/'),
        ),
    ]
